name: SurvivalGame
version: 1.0
main: org.red.survival.SurvivalGame
api-version: '1.18'
authors: [Arlecchino, RedKiller]
depend:
  - CommediaDell_arte
description: zzzzzzz


commands:
  job:
    description: "get job book command"
    permission: op
